/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define I2C1_EV_IRQ		31
#define TIM2_IRQ		28

// memory map registers

uint32_t *pNVIC_ISERBase = (uint32_t*)0xE000E100;
uint32_t *pNVIC_ISPRBase = (uint32_t*)0XE000E200;
uint32_t *pNVIC_IPRBase = (uint32_t*)0xE000E400;

void config_interrupt_priority(uint8_t irq_no, uint8_t priority)
{
	// iprx register for irq
	uint8_t iprx = irq_no / 4;
	uint32_t *ipr = pNVIC_IPRBase + iprx;

	// iprx bit position
	uint8_t pos = (irq_no % 4) * 8;

	// configure the priority
	*ipr &= ~(0xFF << pos); // clear
	*ipr |= (priority << pos); // set value
}

int main(void)
{
	// set priority
	config_interrupt_priority(I2C1_EV_IRQ, 0x80);
	//config_interrupt_priority(TIM2_IRQ, 0x80);	// set at same priority
	config_interrupt_priority(TIM2_IRQ, 0x70); // set w8ith higher priority

	// set the interrupt pending bit (force)
	*pNVIC_ISPRBase |= (0x01 << I2C1_EV_IRQ);

	// enable interrupt
	*pNVIC_ISERBase |= (0x01 << I2C1_EV_IRQ);

	/* Loop forever */
	for(;;);
}

void I2C1_EV_IRQHandler(void)
{
	*pNVIC_ISERBase |= (0x01 << TIM2_IRQ);
	*pNVIC_ISPRBase |= (0x01 << TIM2_IRQ);	// force pend timer2 interrupt here
	printf("I2C1_EV_IRQHandler\n");
	while(1); // add while loop here with same timer two priority to check if pre-empt works. does not pre-empt with same priority
}


void TIM2_IRQHandler(void)
{
	printf("TIM2_IRQHandler\n");
}

