/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void HardFault_Handler(void)
{
	printf("hard fault received\n");
}

void gen_interrupt(void)
{
	uint32_t *pSTIR  = (uint32_t *)0xE000EF00;
	uint32_t *pISER0 = (uint32_t *)0xE000E100;

	// enable IRQ3 interrupt
	*pISER0 |= (1 << 3);

	// generate an interrupt from software from IRQ3
	*pSTIR = (3 & 0x1FF);
}

void change_privilege(void)
{
	//read
	__asm volatile ("MRS R0, CONTROL");

	// modify - change to unprivileged
	__asm volatile ("ORR R0, R0, #0x01");

	// write
	__asm volatile ("MSR CONTROL, R0");

}

int main(void)
{
    /* Loop forever */

#if 0 // check changing privilege mode
	change_privilege();

	gen_interrupt();
#endif

	// check thumb instruction bit (tbit) - cortex m processor this should be set to 1
	// as cortex m only support thumb instructions. 0 measns ARM instructions which are not
	// supported. setting 0 causes hard fault

	void (*my_func)(void);

	my_func=0x8000200;	// figure out the address of gen_interrupt function from the .list file
						// compiler adds 0x01 to this value automatically

	my_func();

	for(;;);
}
